// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/messages.proto

package com.yahoo.ycsb.db;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mydb.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
     */
    com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE getType();

    /**
     * <code>string table = 2;</code>
     */
    java.lang.String getTable();
    /**
     * <code>string table = 2;</code>
     */
    com.google.protobuf.ByteString
        getTableBytes();

    /**
     * <code>string key = 3;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>repeated string fields = 4;</code>
     */
    java.util.List<java.lang.String>
        getFieldsList();
    /**
     * <code>repeated string fields = 4;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated string fields = 4;</code>
     */
    java.lang.String getFields(int index);
    /**
     * <code>repeated string fields = 4;</code>
     */
    com.google.protobuf.ByteString
        getFieldsBytes(int index);

    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */
    int getTextRowCount();
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */
    boolean containsTextRow(
        java.lang.String key);
    /**
     * Use {@link #getTextRowMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getTextRow();
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getTextRowMap();
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    com.google.protobuf.ByteString getTextRowOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    com.google.protobuf.ByteString getTextRowOrThrow(
        java.lang.String key);

    /**
     * <code>string long_field = 6;</code>
     */
    java.lang.String getLongField();
    /**
     * <code>string long_field = 6;</code>
     */
    com.google.protobuf.ByteString
        getLongFieldBytes();

    /**
     * <code>sint64 long_row = 7;</code>
     */
    long getLongRow();
  }
  /**
   * Protobuf type {@code mydb.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mydb.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      type_ = 0;
      table_ = "";
      key_ = "";
      fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      longField_ = "";
      longRow_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              table_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              fields_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                textRow_ = com.google.protobuf.MapField.newMapField(
                    TextRowDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              textRow__ = input.readMessage(
                  TextRowDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              textRow_.getMutableMap().put(
                  textRow__.getKey(), textRow__.getValue());
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              longField_ = s;
              break;
            }
            case 56: {

              longRow_ = input.readSInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          fields_ = fields_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetTextRow();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.Messages.Request.class, com.yahoo.ycsb.db.Messages.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code mydb.Request.REQUEST_TYPE}
     */
    public enum REQUEST_TYPE
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INSERT_TEXT = 0;</code>
       */
      INSERT_TEXT(0),
      /**
       * <code>INSERT_LONG = 1;</code>
       */
      INSERT_LONG(1),
      /**
       * <code>READ_TEXT = 2;</code>
       */
      READ_TEXT(2),
      /**
       * <code>READ_LONG = 3;</code>
       */
      READ_LONG(3),
      /**
       * <code>UPDATE_TEXT = 4;</code>
       */
      UPDATE_TEXT(4),
      /**
       * <code>UPDATE_LONG = 5;</code>
       */
      UPDATE_LONG(5),
      /**
       * <code>DELETE = 6;</code>
       */
      DELETE(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>INSERT_TEXT = 0;</code>
       */
      public static final int INSERT_TEXT_VALUE = 0;
      /**
       * <code>INSERT_LONG = 1;</code>
       */
      public static final int INSERT_LONG_VALUE = 1;
      /**
       * <code>READ_TEXT = 2;</code>
       */
      public static final int READ_TEXT_VALUE = 2;
      /**
       * <code>READ_LONG = 3;</code>
       */
      public static final int READ_LONG_VALUE = 3;
      /**
       * <code>UPDATE_TEXT = 4;</code>
       */
      public static final int UPDATE_TEXT_VALUE = 4;
      /**
       * <code>UPDATE_LONG = 5;</code>
       */
      public static final int UPDATE_LONG_VALUE = 5;
      /**
       * <code>DELETE = 6;</code>
       */
      public static final int DELETE_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static REQUEST_TYPE valueOf(int value) {
        return forNumber(value);
      }

      public static REQUEST_TYPE forNumber(int value) {
        switch (value) {
          case 0: return INSERT_TEXT;
          case 1: return INSERT_LONG;
          case 2: return READ_TEXT;
          case 3: return READ_LONG;
          case 4: return UPDATE_TEXT;
          case 5: return UPDATE_LONG;
          case 6: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<REQUEST_TYPE>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          REQUEST_TYPE> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<REQUEST_TYPE>() {
              public REQUEST_TYPE findValueByNumber(int number) {
                return REQUEST_TYPE.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Messages.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final REQUEST_TYPE[] VALUES = values();

      public static REQUEST_TYPE valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private REQUEST_TYPE(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mydb.Request.REQUEST_TYPE)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
     */
    public com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE getType() {
      com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE result = com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.valueOf(type_);
      return result == null ? com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.UNRECOGNIZED : result;
    }

    public static final int TABLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object table_;
    /**
     * <code>string table = 2;</code>
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        table_ = s;
        return s;
      }
    }
    /**
     * <code>string table = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 3;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList fields_;
    /**
     * <code>repeated string fields = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated string fields = 4;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated string fields = 4;</code>
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated string fields = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }

    public static final int TEXT_ROW_FIELD_NUMBER = 5;
    private static final class TextRowDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_TextRowEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> textRow_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetTextRow() {
      if (textRow_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TextRowDefaultEntryHolder.defaultEntry);
      }
      return textRow_;
    }

    public int getTextRowCount() {
      return internalGetTextRow().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    public boolean containsTextRow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTextRow().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTextRowMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextRow() {
      return getTextRowMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextRowMap() {
      return internalGetTextRow().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    public com.google.protobuf.ByteString getTextRowOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetTextRow().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; text_row = 5;</code>
     */

    public com.google.protobuf.ByteString getTextRowOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetTextRow().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LONG_FIELD_FIELD_NUMBER = 6;
    private volatile java.lang.Object longField_;
    /**
     * <code>string long_field = 6;</code>
     */
    public java.lang.String getLongField() {
      java.lang.Object ref = longField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longField_ = s;
        return s;
      }
    }
    /**
     * <code>string long_field = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLongFieldBytes() {
      java.lang.Object ref = longField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONG_ROW_FIELD_NUMBER = 7;
    private long longRow_;
    /**
     * <code>sint64 long_row = 7;</code>
     */
    public long getLongRow() {
      return longRow_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.INSERT_TEXT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getTableBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, table_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fields_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTextRow(),
          TextRowDefaultEntryHolder.defaultEntry,
          5);
      if (!getLongFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, longField_);
      }
      if (longRow_ != 0L) {
        output.writeSInt64(7, longRow_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.INSERT_TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getTableBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, table_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += computeStringSizeNoTag(fields_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetTextRow().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
        textRow__ = TextRowDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, textRow__);
      }
      if (!getLongFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, longField_);
      }
      if (longRow_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(7, longRow_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yahoo.ycsb.db.Messages.Request)) {
        return super.equals(obj);
      }
      com.yahoo.ycsb.db.Messages.Request other = (com.yahoo.ycsb.db.Messages.Request) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getTable()
          .equals(other.getTable());
      result = result && getKey()
          .equals(other.getKey());
      result = result && getFieldsList()
          .equals(other.getFieldsList());
      result = result && internalGetTextRow().equals(
          other.internalGetTextRow());
      result = result && getLongField()
          .equals(other.getLongField());
      result = result && (getLongRow()
          == other.getLongRow());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + TABLE_FIELD_NUMBER;
      hash = (53 * hash) + getTable().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      if (!internalGetTextRow().getMap().isEmpty()) {
        hash = (37 * hash) + TEXT_ROW_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTextRow().hashCode();
      }
      hash = (37 * hash) + LONG_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getLongField().hashCode();
      hash = (37 * hash) + LONG_ROW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongRow());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yahoo.ycsb.db.Messages.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mydb.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mydb.Request)
        com.yahoo.ycsb.db.Messages.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetTextRow();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableTextRow();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.Messages.Request.class, com.yahoo.ycsb.db.Messages.Request.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.Messages.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        table_ = "";

        key_ = "";

        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableTextRow().clear();
        longField_ = "";

        longRow_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Request_descriptor;
      }

      public com.yahoo.ycsb.db.Messages.Request getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.Messages.Request.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.Messages.Request build() {
        com.yahoo.ycsb.db.Messages.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.Messages.Request buildPartial() {
        com.yahoo.ycsb.db.Messages.Request result = new com.yahoo.ycsb.db.Messages.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.table_ = table_;
        result.key_ = key_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          fields_ = fields_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fields_ = fields_;
        result.textRow_ = internalGetTextRow();
        result.textRow_.makeImmutable();
        result.longField_ = longField_;
        result.longRow_ = longRow_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.Messages.Request) {
          return mergeFrom((com.yahoo.ycsb.db.Messages.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.Messages.Request other) {
        if (other == com.yahoo.ycsb.db.Messages.Request.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getTable().isEmpty()) {
          table_ = other.table_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        internalGetMutableTextRow().mergeFrom(
            other.internalGetTextRow());
        if (!other.getLongField().isEmpty()) {
          longField_ = other.longField_;
          onChanged();
        }
        if (other.getLongRow() != 0L) {
          setLongRow(other.getLongRow());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.Messages.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.Messages.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
       */
      public com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE getType() {
        com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE result = com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.valueOf(type_);
        return result == null ? com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
       */
      public Builder setType(com.yahoo.ycsb.db.Messages.Request.REQUEST_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mydb.Request.REQUEST_TYPE type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object table_ = "";
      /**
       * <code>string table = 2;</code>
       */
      public java.lang.String getTable() {
        java.lang.Object ref = table_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          table_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string table = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTableBytes() {
        java.lang.Object ref = table_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          table_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string table = 2;</code>
       */
      public Builder setTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        table_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string table = 2;</code>
       */
      public Builder clearTable() {
        
        table_ = getDefaultInstance().getTable();
        onChanged();
        return this;
      }
      /**
       * <code>string table = 2;</code>
       */
      public Builder setTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        table_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 3;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldsList() {
        return fields_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public java.lang.String getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFieldsBytes(int index) {
        return fields_.getByteString(index);
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public Builder setFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public Builder addFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public Builder clearFields() {
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 4;</code>
       */
      public Builder addFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.ByteString> textRow_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetTextRow() {
        if (textRow_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TextRowDefaultEntryHolder.defaultEntry);
        }
        return textRow_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetMutableTextRow() {
        onChanged();;
        if (textRow_ == null) {
          textRow_ = com.google.protobuf.MapField.newMapField(
              TextRowDefaultEntryHolder.defaultEntry);
        }
        if (!textRow_.isMutable()) {
          textRow_ = textRow_.copy();
        }
        return textRow_;
      }

      public int getTextRowCount() {
        return internalGetTextRow().getMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public boolean containsTextRow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTextRow().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTextRowMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextRow() {
        return getTextRowMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextRowMap() {
        return internalGetTextRow().getMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public com.google.protobuf.ByteString getTextRowOrDefault(
          java.lang.String key,
          com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetTextRow().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public com.google.protobuf.ByteString getTextRowOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetTextRow().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTextRow() {
        internalGetMutableTextRow().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public Builder removeTextRow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTextRow().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
      getMutableTextRow() {
        return internalGetMutableTextRow().getMutableMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */
      public Builder putTextRow(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTextRow().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_row = 5;</code>
       */

      public Builder putAllTextRow(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        internalGetMutableTextRow().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object longField_ = "";
      /**
       * <code>string long_field = 6;</code>
       */
      public java.lang.String getLongField() {
        java.lang.Object ref = longField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string long_field = 6;</code>
       */
      public com.google.protobuf.ByteString
          getLongFieldBytes() {
        java.lang.Object ref = longField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string long_field = 6;</code>
       */
      public Builder setLongField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        longField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string long_field = 6;</code>
       */
      public Builder clearLongField() {
        
        longField_ = getDefaultInstance().getLongField();
        onChanged();
        return this;
      }
      /**
       * <code>string long_field = 6;</code>
       */
      public Builder setLongFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        longField_ = value;
        onChanged();
        return this;
      }

      private long longRow_ ;
      /**
       * <code>sint64 long_row = 7;</code>
       */
      public long getLongRow() {
        return longRow_;
      }
      /**
       * <code>sint64 long_row = 7;</code>
       */
      public Builder setLongRow(long value) {
        
        longRow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 long_row = 7;</code>
       */
      public Builder clearLongRow() {
        
        longRow_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mydb.Request)
    }

    // @@protoc_insertion_point(class_scope:mydb.Request)
    private static final com.yahoo.ycsb.db.Messages.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yahoo.ycsb.db.Messages.Request();
    }

    public static com.yahoo.ycsb.db.Messages.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.yahoo.ycsb.db.Messages.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mydb.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
     */
    com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE getType();

    /**
     * <code>bool isStatusOk = 2;</code>
     */
    boolean getIsStatusOk();

    /**
     * <code>string long_result = 3;</code>
     */
    java.lang.String getLongResult();
    /**
     * <code>string long_result = 3;</code>
     */
    com.google.protobuf.ByteString
        getLongResultBytes();

    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */
    int getTextResultCount();
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */
    boolean containsTextResult(
        java.lang.String key);
    /**
     * Use {@link #getTextResultMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getTextResult();
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getTextResultMap();
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    com.google.protobuf.ByteString getTextResultOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    com.google.protobuf.ByteString getTextResultOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code mydb.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mydb.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      type_ = 0;
      isStatusOk_ = false;
      longResult_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              isStatusOk_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              longResult_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                textResult_ = com.google.protobuf.MapField.newMapField(
                    TextResultDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              textResult__ = input.readMessage(
                  TextResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              textResult_.getMutableMap().put(
                  textResult__.getKey(), textResult__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetTextResult();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yahoo.ycsb.db.Messages.Response.class, com.yahoo.ycsb.db.Messages.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code mydb.Response.RESPONSE_TYPE}
     */
    public enum RESPONSE_TYPE
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READ_TEXT = 0;</code>
       */
      READ_TEXT(0),
      /**
       * <code>READ_LONG = 1;</code>
       */
      READ_LONG(1),
      /**
       * <code>STATUS = 2;</code>
       */
      STATUS(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>READ_TEXT = 0;</code>
       */
      public static final int READ_TEXT_VALUE = 0;
      /**
       * <code>READ_LONG = 1;</code>
       */
      public static final int READ_LONG_VALUE = 1;
      /**
       * <code>STATUS = 2;</code>
       */
      public static final int STATUS_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RESPONSE_TYPE valueOf(int value) {
        return forNumber(value);
      }

      public static RESPONSE_TYPE forNumber(int value) {
        switch (value) {
          case 0: return READ_TEXT;
          case 1: return READ_LONG;
          case 2: return STATUS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RESPONSE_TYPE>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RESPONSE_TYPE> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RESPONSE_TYPE>() {
              public RESPONSE_TYPE findValueByNumber(int number) {
                return RESPONSE_TYPE.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Messages.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final RESPONSE_TYPE[] VALUES = values();

      public static RESPONSE_TYPE valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RESPONSE_TYPE(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mydb.Response.RESPONSE_TYPE)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
     */
    public com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE getType() {
      com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE result = com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.valueOf(type_);
      return result == null ? com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.UNRECOGNIZED : result;
    }

    public static final int ISSTATUSOK_FIELD_NUMBER = 2;
    private boolean isStatusOk_;
    /**
     * <code>bool isStatusOk = 2;</code>
     */
    public boolean getIsStatusOk() {
      return isStatusOk_;
    }

    public static final int LONG_RESULT_FIELD_NUMBER = 3;
    private volatile java.lang.Object longResult_;
    /**
     * <code>string long_result = 3;</code>
     */
    public java.lang.String getLongResult() {
      java.lang.Object ref = longResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longResult_ = s;
        return s;
      }
    }
    /**
     * <code>string long_result = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLongResultBytes() {
      java.lang.Object ref = longResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_RESULT_FIELD_NUMBER = 4;
    private static final class TextResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_TextResultEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> textResult_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetTextResult() {
      if (textResult_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TextResultDefaultEntryHolder.defaultEntry);
      }
      return textResult_;
    }

    public int getTextResultCount() {
      return internalGetTextResult().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    public boolean containsTextResult(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTextResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTextResultMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextResult() {
      return getTextResultMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextResultMap() {
      return internalGetTextResult().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    public com.google.protobuf.ByteString getTextResultOrDefault(
        java.lang.String key,
        com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetTextResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; text_result = 4;</code>
     */

    public com.google.protobuf.ByteString getTextResultOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetTextResult().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.READ_TEXT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (isStatusOk_ != false) {
        output.writeBool(2, isStatusOk_);
      }
      if (!getLongResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, longResult_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTextResult(),
          TextResultDefaultEntryHolder.defaultEntry,
          4);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.READ_TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (isStatusOk_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isStatusOk_);
      }
      if (!getLongResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, longResult_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetTextResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
        textResult__ = TextResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, textResult__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yahoo.ycsb.db.Messages.Response)) {
        return super.equals(obj);
      }
      com.yahoo.ycsb.db.Messages.Response other = (com.yahoo.ycsb.db.Messages.Response) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getIsStatusOk()
          == other.getIsStatusOk());
      result = result && getLongResult()
          .equals(other.getLongResult());
      result = result && internalGetTextResult().equals(
          other.internalGetTextResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ISSTATUSOK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsStatusOk());
      hash = (37 * hash) + LONG_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getLongResult().hashCode();
      if (!internalGetTextResult().getMap().isEmpty()) {
        hash = (37 * hash) + TEXT_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTextResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yahoo.ycsb.db.Messages.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yahoo.ycsb.db.Messages.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mydb.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mydb.Response)
        com.yahoo.ycsb.db.Messages.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetTextResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableTextResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yahoo.ycsb.db.Messages.Response.class, com.yahoo.ycsb.db.Messages.Response.Builder.class);
      }

      // Construct using com.yahoo.ycsb.db.Messages.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        isStatusOk_ = false;

        longResult_ = "";

        internalGetMutableTextResult().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ycsb.db.Messages.internal_static_mydb_Response_descriptor;
      }

      public com.yahoo.ycsb.db.Messages.Response getDefaultInstanceForType() {
        return com.yahoo.ycsb.db.Messages.Response.getDefaultInstance();
      }

      public com.yahoo.ycsb.db.Messages.Response build() {
        com.yahoo.ycsb.db.Messages.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yahoo.ycsb.db.Messages.Response buildPartial() {
        com.yahoo.ycsb.db.Messages.Response result = new com.yahoo.ycsb.db.Messages.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.isStatusOk_ = isStatusOk_;
        result.longResult_ = longResult_;
        result.textResult_ = internalGetTextResult();
        result.textResult_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ycsb.db.Messages.Response) {
          return mergeFrom((com.yahoo.ycsb.db.Messages.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yahoo.ycsb.db.Messages.Response other) {
        if (other == com.yahoo.ycsb.db.Messages.Response.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getIsStatusOk() != false) {
          setIsStatusOk(other.getIsStatusOk());
        }
        if (!other.getLongResult().isEmpty()) {
          longResult_ = other.longResult_;
          onChanged();
        }
        internalGetMutableTextResult().mergeFrom(
            other.internalGetTextResult());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yahoo.ycsb.db.Messages.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yahoo.ycsb.db.Messages.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
       */
      public com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE getType() {
        com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE result = com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.valueOf(type_);
        return result == null ? com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
       */
      public Builder setType(com.yahoo.ycsb.db.Messages.Response.RESPONSE_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mydb.Response.RESPONSE_TYPE type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean isStatusOk_ ;
      /**
       * <code>bool isStatusOk = 2;</code>
       */
      public boolean getIsStatusOk() {
        return isStatusOk_;
      }
      /**
       * <code>bool isStatusOk = 2;</code>
       */
      public Builder setIsStatusOk(boolean value) {
        
        isStatusOk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isStatusOk = 2;</code>
       */
      public Builder clearIsStatusOk() {
        
        isStatusOk_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object longResult_ = "";
      /**
       * <code>string long_result = 3;</code>
       */
      public java.lang.String getLongResult() {
        java.lang.Object ref = longResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string long_result = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLongResultBytes() {
        java.lang.Object ref = longResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string long_result = 3;</code>
       */
      public Builder setLongResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        longResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string long_result = 3;</code>
       */
      public Builder clearLongResult() {
        
        longResult_ = getDefaultInstance().getLongResult();
        onChanged();
        return this;
      }
      /**
       * <code>string long_result = 3;</code>
       */
      public Builder setLongResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        longResult_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.ByteString> textResult_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetTextResult() {
        if (textResult_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TextResultDefaultEntryHolder.defaultEntry);
        }
        return textResult_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
      internalGetMutableTextResult() {
        onChanged();;
        if (textResult_ == null) {
          textResult_ = com.google.protobuf.MapField.newMapField(
              TextResultDefaultEntryHolder.defaultEntry);
        }
        if (!textResult_.isMutable()) {
          textResult_ = textResult_.copy();
        }
        return textResult_;
      }

      public int getTextResultCount() {
        return internalGetTextResult().getMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public boolean containsTextResult(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTextResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTextResultMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextResult() {
        return getTextResultMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getTextResultMap() {
        return internalGetTextResult().getMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public com.google.protobuf.ByteString getTextResultOrDefault(
          java.lang.String key,
          com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetTextResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public com.google.protobuf.ByteString getTextResultOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetTextResult().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTextResult() {
        internalGetMutableTextResult().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public Builder removeTextResult(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTextResult().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
      getMutableTextResult() {
        return internalGetMutableTextResult().getMutableMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */
      public Builder putTextResult(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTextResult().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; text_result = 4;</code>
       */

      public Builder putAllTextResult(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        internalGetMutableTextResult().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mydb.Response)
    }

    // @@protoc_insertion_point(class_scope:mydb.Response)
    private static final com.yahoo.ycsb.db.Messages.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yahoo.ycsb.db.Messages.Response();
    }

    public static com.yahoo.ycsb.db.Messages.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.yahoo.ycsb.db.Messages.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mydb_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mydb_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mydb_Request_TextRowEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mydb_Request_TextRowEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mydb_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mydb_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mydb_Response_TextResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mydb_Response_TextResultEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protobuf/messages.proto\022\004mydb\"\341\002\n\007Requ" +
      "est\022(\n\004type\030\001 \001(\0162\032.mydb.Request.REQUEST" +
      "_TYPE\022\r\n\005table\030\002 \001(\t\022\013\n\003key\030\003 \001(\t\022\016\n\006fie" +
      "lds\030\004 \003(\t\022,\n\010text_row\030\005 \003(\0132\032.mydb.Reque" +
      "st.TextRowEntry\022\022\n\nlong_field\030\006 \001(\t\022\020\n\010l" +
      "ong_row\030\007 \001(\022\032.\n\014TextRowEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"|\n\014REQUEST_TYPE\022\017\n" +
      "\013INSERT_TEXT\020\000\022\017\n\013INSERT_LONG\020\001\022\r\n\tREAD_" +
      "TEXT\020\002\022\r\n\tREAD_LONG\020\003\022\017\n\013UPDATE_TEXT\020\004\022\017" +
      "\n\013UPDATE_LONG\020\005\022\n\n\006DELETE\020\006\"\202\002\n\010Response",
      "\022*\n\004type\030\001 \001(\0162\034.mydb.Response.RESPONSE_" +
      "TYPE\022\022\n\nisStatusOk\030\002 \001(\010\022\023\n\013long_result\030" +
      "\003 \001(\t\0223\n\013text_result\030\004 \003(\0132\036.mydb.Respon" +
      "se.TextResultEntry\0321\n\017TextResultEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"9\n\rRESPONS" +
      "E_TYPE\022\r\n\tREAD_TEXT\020\000\022\r\n\tREAD_LONG\020\001\022\n\n\006" +
      "STATUS\020\002B\035\n\021com.yahoo.ycsb.dbB\010Messagesb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mydb_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mydb_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mydb_Request_descriptor,
        new java.lang.String[] { "Type", "Table", "Key", "Fields", "TextRow", "LongField", "LongRow", });
    internal_static_mydb_Request_TextRowEntry_descriptor =
      internal_static_mydb_Request_descriptor.getNestedTypes().get(0);
    internal_static_mydb_Request_TextRowEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mydb_Request_TextRowEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mydb_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mydb_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mydb_Response_descriptor,
        new java.lang.String[] { "Type", "IsStatusOk", "LongResult", "TextResult", });
    internal_static_mydb_Response_TextResultEntry_descriptor =
      internal_static_mydb_Response_descriptor.getNestedTypes().get(0);
    internal_static_mydb_Response_TextResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mydb_Response_TextResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
